const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function beginnerIntro(l){const b=l.beginner;if(!b)return '';return `<section class="beginner-intro"><span class="section-kicker">СНАЧАЛА ЧЕЛОВЕЧЕСКИМ ЯЗЫКОМ</span><h3>Зачем это нужно</h3><p>${e(b.why)}</p><div class="everyday"><b>Представь обычную ситуацию</b><p>${e(b.analogy)}</p></div><h3>Как узнать такую задачу</h3><p>${e(b.recognition)}</p></section>`;}
const worked=(steps,terms)=>`<details class="beginner-details" open><summary>Разберём на числах, шаг за шагом</summary><ol class="worked-steps">${steps.map(s=>`<li>${e(s)}</li>`).join('')}</ol></details>${terms?.length?`<details class="beginner-details"><summary>Что означает каждая команда</summary><dl class="command-dictionary">${terms.map(([code,text])=>`<dt><code>${e(code)}</code></dt><dd>${e(text)}</dd>`).join('')}</dl></details>`:''}`;
export function beginnerDetails(l){const b=l.beginner;if(!b)return '';return worked(b.steps,b.terms);}
export function practiceIntro(l){const p=l.practice;if(!p)return '';return `<section class="beginner-intro"><span class="section-kicker">СТУПЕНЬКА ${l.rung} · ${l.rung===1?'ПО ОБРАЗЦУ':'БЕЗ ОБРАЗЦА'}</span><h3>Что тренируем</h3><p>${e(p.goal)}</p><div class="everyday"><b>${l.rung===1?'В редакторе уже есть заготовка':'Решение пишешь почти полностью'}</b><p>${l.rung===1?'Прочитай её сверху вниз, найди комментарий с подсказкой и допиши недостающее. Остальной код уже работает.':'Опирайся на пример и разбор ниже. Подсказки открывай по одной; если не хватит — открой решение по строке.'}</p></div></section>`;}
export function practiceDetails(l){const p=l.practice;if(!p)return '';return worked(p.walk,p.terms);}
export function codeWalkthrough(l){return l.lineNotes?`<details class="line-walkthrough"><summary>Объяснить решение построчно</summary><ol>${l.lineNotes.map(n=>`<li><span class="line-number">${n.line}</span><div><code>${e(n.code)}</code><p>${e(n.text)}</p></div></li>`).join('')}</ol></details>`:'';}
export function firstSteps(){const items=[
['Что такое программа','Список точных инструкций','Python читает команды сверху вниз. Алгоритм — порядок действий для решения задачи. Текст заключаем в кавычки, вычисления пишем без них. Скобки показывают, с чем работает команда.', 'print("Привет")\nprint(2 + 3)  # ответ 5', 'Сначала появится Привет, затем 5. Знак # начинает комментарий для человека; Python его пропускает.'],
['Что такое переменная','Имя для значения','В первой строке запоминаем число 3 под именем apples. Во второй сначала считаем правую часть, затем заменяем прежнее значение новым.', 'apples = 3\napples = apples + 2\nprint(apples)  # 5', '= означает «сохрани», а == означает «сравни». Имена выбираем сами: total — итог, count — количество. Не называй переменные print или input: эти имена уже обозначают команды.'],
['Куда вводить числа','Код и вход — разные поля','В редактор пишем инструкцию. В поле «Входные данные» — числа для неё. input() читает одну строку этого поля: не нужно ждать приглашения в консоли.', 'text = input()      # если ввод 7, получим текст "7"\nnumber = int(text)  # превратим его в число\nprint(number + 1)  # 8', 'Текст "7" + "1" даёт "71", а числа 7 + 1 дают 8. Поэтому после input часто нужен int.'],
['Как прочитать два числа','Сначала длинно, затем короче','Пусть в поле ввода записано 2 3. Разделим строку по пробелу и превратим каждый кусочек в число.', 'line = input()       # "2 3"\nparts = line.split() # ["2", "3"]\na = int(parts[0])    # 2\nb = int(parts[1])    # 3\nprint(a + b)         # 5\n\n# Короткая запись чтения тех же чисел:\n# a, b = map(int, input().split())', 'parts[0] — первый кусочек, parts[1] — второй: индексы начинаются с 0. map(int, …) применяет int к каждому кусочку. Начинай с длинной записи, если так понятнее.'],
['Зачем отступы','Пробелы показывают вложенность','После if и циклов ставим двоеточие. Четыре пробела показывают строки внутри блока. На телефоне для этого есть кнопка «Отступ» рядом с редактором.', 'age = 18\nif age >= 18:\n    print("Можно")  # только когда условие верно\nprint("Готово")     # всегда, вне условия', 'Не смешивай Tab и пробелы вручную. Кнопка отступа вставляет четыре пробела. Код в этом курсе можно писать полностью на экранной клавиатуре.'],
['Как проверять себя','Две кнопки — два действия','«Запустить» выполняет код с твоим вводом. «Проверить решение» пробует подготовленные входы и сравнивает ответы. Один удачный пример ещё не доказывает правильность.', '# Не печатай лишних приглашений:\n# print("Введите число")  # лишний вывод для задачи\nn = int(input())\nprint(n + 1)', 'При ошибке читай последнюю строку. solution.py, line 3 означает строку 3 твоего кода. Исправляй одну причину за раз: красный результат показывает, что проверить.']];
return `<div class="page-intro"><div><div class="eyebrow">НУЛЕВОЙ ШАГ · 8 МИНУТ</div><h1>Никогда не писал код? Начнём.</h1><p>Ничего устанавливать на телефон не нужно. Одно объяснение — одно маленькое действие.</p></div></div><div class="first-steps">${items.map((v,i)=>`<section><span class="step-label">0${i+1} / ${e(v[0])}</span><h2>${e(v[1])}</h2><p>${e(v[2])}</p><pre class="example-code">${e(v[3])}</pre><p>${e(v[4])}</p>${i===0?'<a class="button primary" href="#lesson/warmup-input">Попробовать одну команду →</a>':''}</section>`).join('')}</div><div class="everyday"><b>Порядок занятия</b><p>Понять зачем → разминка → ступенька по образцу → ступенька без образца → основная задача → проверка → объяснить решение своими словами. Если трудно, открой одну подсказку, затем решение по одной строке. Полный разбор оставь напоследок.</p></div><a class="button primary" href="#lesson/warmup-input">Начать с самой простой практики →</a>`;}
